version: '3.7'

services:
    db:
        # build: ./database/postgres
        image: postgres:latest
        # TODO replace latest by the number of the last version
        container_name: pong_db_cnt
        expose:
            - "5432"
        # volumes:
        #     - ./mongodb/db_data:/data/db
        #     - ./mongodb/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
        # TODO voir networks in docker
        # networks: 
        #     - backend
        restart: always
        environment: 
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DATABASE=ft_transcendance

    pgadmin:
        build: ./database/pgadmin
        image: pong_pgadmin_img
        container_name: pong_pgadmin_cnt
        restart: always
    backend:
        # depends_on: 
        #     - db
        build: ./backend
        image: pong_back_img
        container_name: pong_back_cnt
        ports:
            - "8800:8800"
            - "465:465"
        volumes:
            - './backend/srcs/:/app/'
            # - '/app/node_modules'
            #REVIEW - delete upper line (?)
        restart: always
        # networks: 
        #     - backend
        # links:
        #     - "db:mongodb"
        # environment:
        #     - DB_USER=nlecaill
        #     - DB_PASSWORD=nlecaill

    frontend:
        build: ./frontend
        image: pong_front_img
        container_name: pong_front_cnt
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend/srcs/:/app/
            - /app/node_modules
        # networks: 
        #     - backend
        #     - frontend
# networks: 
    # frontend: {}
    # backend: {}
# volumes:
    # db_data: {}