version: '3.7'

services:
    db:
        # build: ./database/postgres
        # image: pong_db_img
        image: postgres:13
        container_name: pong_db_cnt
        expose:
            - "5432"
        networks: 
            - pong_database_network
        restart: always
        volumes:
             - pg_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DB=ft_transcendance
            - PG_DATA=/var/lib/postgresql/data

    pgadmin:
        depends_on: 
            - db
        # build: ./database/pgadmin
        # image: pong_pgadmin_img
        image: dpage/pgadmin4
        container_name: pong_pgadmin_cnt
        restart: always
        ports:
            - "80:80"
        networks:
            - pong_database_network
        environment: 
            - PGADMIN_DEFAULT_EMAIL=lecaille.nathan@outlook.fr
            - PGADMIN_DEFAULT_PASSWORD=1234
    backend:
        depends_on: 
            - db
        build: ./backend
        image: pong_back_img
        container_name: pong_back_cnt
        ports:
            - "8800:8800"
            - "465:465"
        volumes:
            - './backend/srcs/:/app/'
        restart: always
        networks: 
            - pong_database_network
            - pong_backend_network

    frontend:
        build: ./frontend
        image: pong_front_img
        container_name: pong_front_cnt
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend/srcs/:/app/
        networks: 
            - pong_backend_network
            - pong_frontend_network
networks: 
    pong_database_network : {}
    pong_frontend_network : {}
    pong_backend_network : {}
    
volumes:
    pg_data: 
