version: '3.7'

services:
    db:
        # build: ./database/postgres
        # image: pong_db_img
        image: postgres:13
        container_name: pong_db_cnt
        expose:
            - "5432"
        networks: 
            - pong_database_network
        restart: always
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file:
            - ./database/postgres/postgres.env

    pgadmin:
        depends_on: 
            - db
        # build: ./database/pgadmin
        # image: pong_pgadmin_img
        image: dpage/pgadmin4
        container_name: pong_pgadmin_cnt
        restart: always
        ports:
            - "80:80"
        networks:
            - pong_database_network
        env_file:
            - ./database/pgadmin/pgadmin.env

    backend:
        depends_on: 
            - db
        build: ./backend
        image: pong_back_img
        container_name: pong_back_cnt
        ports:
            - "8800:8800"
            - "465:465"
        volumes:
            - './backend/srcs/:/app/'
        restart: always
        networks: 
            - pong_database_network
            - pong_backend_network

    frontend:
        build: ./frontend
        image: pong_front_img
        container_name: pong_front_cnt
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend/srcs/:/app/
            - /app/node_modules
        networks: 
            - pong_backend_network
            - pong_frontend_network

networks: 
    pong_database_network : {}
    pong_frontend_network : {}
    pong_backend_network : {}

volumes:
    pg_data: 
