
export const LIB_VERTICAL_SINGLE = "LIB_VERTICAL_SINGLE";
export const LIB_VERTICAL_MULTI = "LIB_VERTICAL_MULTI";
export const LIB_HORIZONTAL_SINGLE = "LIB_HORIZONTAL_SINGLE";
export const LIB_HORIZONTAL_MULTI = "LIB_HORIZONTAL_MULTI";
