enum LibNames {
    LIB_VERTICAL_SINGLE = "LIB_VERTICAL_SINGLE",
    LIB_VERTICAL_MULTI = "LIB_VERTICAL_MULTI",
    LIB_HORIZONTAL_SINGLE = "LIB_HORIZONTAL_SINGLE",
    LIB_HORIZONTAL_MULTI = "LIB_HORIZONTAL_MULTI"
}

export default LibNames
